name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to AWS ECR
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app:latest ${{ secrets.AWS_ECR_REGISTRY }}/my-app
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/my-app
